// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUxaJWdUd5PGStMnnDMedVU7Ag6p52vdo',
    appId: '1:1080871328366:ios:5ec5c9d62576d8f51a647f',
    messagingSenderId: '1080871328366',
    projectId: 'lettermusic-8378a',
    storageBucket: 'lettermusic-8378a.firebasestorage.app',
    iosBundleId: 'com.example.lettermusic',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUxaJWdUd5PGStMnnDMedVU7Ag6p52vdo',
    appId: '1:1080871328366:ios:5ec5c9d62576d8f51a647f',
    messagingSenderId: '1080871328366',
    projectId: 'lettermusic-8378a',
    storageBucket: 'lettermusic-8378a.firebasestorage.app',
    iosBundleId: 'com.example.lettermusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLEFfPNcPdSpNbBG9lqoBqjQPfKBP1q9w',
    appId: '1:1080871328366:web:371af9d5ef894e5a1a647f',
    messagingSenderId: '1080871328366',
    projectId: 'lettermusic-8378a',
    authDomain: 'lettermusic-8378a.firebaseapp.com',
    storageBucket: 'lettermusic-8378a.firebasestorage.app',
    measurementId: 'G-MXZ4FX43NR',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLEFfPNcPdSpNbBG9lqoBqjQPfKBP1q9w',
    appId: '1:1080871328366:web:46da1e690513cab81a647f',
    messagingSenderId: '1080871328366',
    projectId: 'lettermusic-8378a',
    authDomain: 'lettermusic-8378a.firebaseapp.com',
    storageBucket: 'lettermusic-8378a.firebasestorage.app',
    measurementId: 'G-9RBTNK1890',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2tGS3rTDsrUib6EkQAU2pIZ80uYA3u1o',
    appId: '1:1080871328366:android:a26aca71b13a0ae01a647f',
    messagingSenderId: '1080871328366',
    projectId: 'lettermusic-8378a',
    storageBucket: 'lettermusic-8378a.firebasestorage.app',
  );
}
